'use client'
import { useState } from 'react'
import Link from 'next/link'
import { ArrowUpRight, FileUp, Layers3, RotateCcw, ScanSearch } from 'lucide-react'
import { Navbar } from './Navbar'
import { BeforeAfterSlider } from '@/components/sections/BeforeAfterSlider'
import { demoHistory, demoMetadata, demoMetrics } from '@/lib/services/mock-data'
import { uploadImage } from '@/lib/services/api'
function Shell({children}:{children:React.ReactNode}){return <><Navbar/><main className="mx-auto max-w-7xl px-6 pb-24 pt-32">{children}</main></>}
function Label({children}:{children:React.ReactNode}){return <p className="mb-5 font-mono text-[10px] uppercase tracking-[.22em] text-cyan">{children}</p>}
export function UploadWorkspace(){const [file,setFile]=useState<string>(); const choose=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){await uploadImage(f);setFile(f.name)}};return <Shell><Label>Workspace / 01 / Upload</Label><div className="grid gap-10 lg:grid-cols-[1.25fr_.75fr]"><div><h1 className="font-mono text-5xl uppercase tracking-[-.07em] sm:text-7xl">Bring an<br/><span className="text-cyan">observation.</span></h1><p className="mt-6 max-w-lg leading-7 text-muted-foreground">Upload a Sentinel-2 GeoTIFF to start a demo enhancement job. Real processing and validation services plug into this same typed boundary.</p><label className="mt-12 flex min-h-72 cursor-pointer flex-col items-center justify-center border border-dashed border-cyan/50 bg-panel p-8 text-center hover:bg-cyan/5"><FileUp className="size-8 text-cyan"/><span className="mt-5 font-mono text-xs uppercase tracking-widest">{file||'Drop GeoTIFF or choose file'}</span><span className="mt-3 text-sm text-muted-foreground">Sentinel-2 MSI · B2 / B3 / B4 / B8</span><input type="file" accept=".tif,.tiff,image/tiff" className="sr-only" onChange={choose}/></label></div><aside className="border border-line bg-panel p-6"><Label>Expected metadata</Label>{Object.entries(demoMetadata).map(([key,value])=><div key={key} className="flex justify-between gap-5 border-b border-line py-4 font-mono text-[11px] uppercase"><span className="text-muted-foreground">{key}</span><span className="text-right text-foreground">{Array.isArray(value)?value.join(' / '):value}</span></div>)}<Link href="/enhance" className="mt-8 flex items-center justify-between border border-cyan px-4 py-3 font-mono text-xs uppercase tracking-widest text-cyan hover:bg-cyan hover:text-ink">Continue to enhance <ArrowUpRight className="size-4"/></Link></aside></div></Shell>}
export function CompareWorkspace(){return <Shell><Label>Workspace / 02 / Compare</Label><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><h1 className="font-mono text-5xl uppercase tracking-[-.07em] sm:text-7xl">Read the<br/><span className="text-cyan">difference.</span></h1><p className="mt-5 text-muted-foreground">DEMO DATA · Drag the divider or focus the handle and use arrow keys.</p></div><div className="flex gap-2 font-mono text-[10px] uppercase"><span className="border border-line px-3 py-2 text-muted-foreground">10 m input</span><span className="border border-cyan px-3 py-2 text-cyan">&lt;4 m target</span></div></div><div className="mt-12"><BeforeAfterSlider/></div><div className="mt-5 flex flex-wrap gap-6 border-b border-line py-5 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{['Sentinel-2 MSI','18 Jun 2024','B2 / B3 / B4 / B8','No reference loaded'].map(x=><span key={x}>{x}</span>)}</div></Shell>}
export function AnalyticsWorkspace(){return <Shell><Label>Workspace / 03 / Analytics</Label><h1 className="max-w-3xl font-mono text-5xl uppercase tracking-[-.07em] sm:text-7xl">A console for<br/><span className="text-cyan">earned confidence.</span></h1><div className="mt-12 grid gap-px bg-line sm:grid-cols-2 lg:grid-cols-4">{[['PSNR','dB'],['SSIM','0–1'],['RMSE','error'],['SAM','degrees']].map(([name,unit])=><div key={name} className="bg-panel p-6"><p className="font-mono text-xs text-muted-foreground">{name} / {unit}</p><p className="mt-10 font-mono text-lg text-cyan">{demoMetrics.status==='awaiting'?'Awaiting validation':'Validated'}</p></div>)}</div><div className="mt-10 grid gap-10 lg:grid-cols-2"><div className="border border-line bg-panel p-8"><Label>Spectral consistency / demo view</Label><div className="flex h-56 items-end gap-4 border-b border-l border-line px-8 pb-0">{[42,64,51,76].map((h,i)=><div key={i} className="flex-1 bg-cyan/60" style={{height:`${h}%`}}><span className="relative -top-6 block text-center font-mono text-[10px] text-muted-foreground">{['B2','B3','B4','B8'][i]}</span></div>)}</div><p className="mt-5 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Illustrative signal shape · demo visualization</p></div><div className="border border-line bg-panel p-8"><Label>Feature visibility</Label>{['Roads','Buildings','Field boundaries','Water','Terrain'].map(x=><div key={x} className="flex items-center justify-between border-b border-line py-4 font-mono text-xs uppercase"><span>{x}</span><span className="text-cyan">Review required</span></div>)}</div></div></Shell>}
export function HistoryWorkspace(){return <Shell><Label>Workspace / 04 / History</Label><div className="flex items-end justify-between"><h1 className="font-mono text-5xl uppercase tracking-[-.07em] sm:text-7xl">Pass<br/><span className="text-cyan">archive.</span></h1><span className="hidden font-mono text-[10px] uppercase text-muted-foreground sm:block">DEMO DATA / 03 records</span></div><div className="mt-12 overflow-x-auto border border-line"><table className="w-full min-w-[760px] text-left font-mono text-xs"><thead className="bg-panel text-[10px] uppercase tracking-widest text-muted-foreground"><tr>{['Dataset','Date','Input','Output','Model','Status','Validation'].map(x=><th key={x} className="p-4 font-normal">{x}</th>)}</tr></thead><tbody>{demoHistory.map(row=><tr key={row.id} className="border-t border-line hover:bg-panel">{[row.dataset,row.date,row.input,row.output,row.model,row.status,row.validation].map((x,i)=><td key={i} className={`p-4 ${i>4?'text-cyan':''}`}>{x}</td>)}</tr>)}</tbody></table></div></Shell>}
export function EnhanceWorkspace(){const [state,setState]=useState('idle');return <Shell><Label>Workspace / 05 / Enhance</Label><div className="grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><h1 className="font-mono text-5xl uppercase tracking-[-.07em] sm:text-7xl">Turn signal<br/><span className="text-cyan">into structure.</span></h1><p className="mt-6 leading-7 text-muted-foreground">A standalone demo of the enhancement state machine. No claims are made until output is checked against reference imagery.</p><button onClick={()=>setState(state==='idle'?'processing':'completed')} className="mt-10 flex items-center gap-3 bg-cyan px-5 py-3 font-mono text-xs uppercase tracking-widest text-ink">{state==='idle'?'Start demo job':state==='processing'?'Processing…':'View result'} <ScanSearch className="size-4"/></button></div><div className="border border-line bg-panel p-8"><div className="flex items-center justify-between font-mono text-xs uppercase"><span>SRM-v1.0-demo</span><span className="text-cyan">{state}</span></div><div className="mt-12 h-2 bg-line"><div className={`h-full bg-cyan transition-all duration-1000 ${state==='idle'?'w-0':state==='processing'?'w-2/3':'w-full'}`}/></div><p className="mt-6 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{state==='completed'?'Ready for review · validation awaiting':'Input → preprocessing → reconstruction → output'}</p>{state==='completed'&&<div className="mt-8"><BeforeAfterSlider compact/></div>}</div></div></Shell>}
